version: 2.1

# add your orb below, to be used in integration tests (note: a @dev:alpha
# release must exist.);
orbs:
  terraform: circleci/terraform@dev:alpha

jobs:
  test-terraform-lifecycle:
    executor: terraform/terraform-executor
    working_directory: "~/src"
    steps:
      - checkout
      - terraform/init:
          path: "~/src"
      - terraform/validate:
          path: "~/src"