version: 2.1

jobs:
  terraform-plan:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Setup Terraform Credentials
          command: |
            mkdir -p ~/.terraform.d
            echo '{"credentials": {"aedifexhack.jfrog.io": {"token": "$JFROG"}}}' > ~/.terraform.d/credentials.tfrc.json
      - run:
          name: Terraform Init
          command: terraform init
#      - run:
#          name: Terraform Plan
#          command: terraform plan -out=tfplan

  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
#      - run:
#          name: Terraform Apply
#          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - terraform-plan
      - terraform-approve:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - terraform-approve
