# CircleCI + Terraform = terracube

version: 2.1

secrets: &secrets
    context: cdk8s

orbs:
  tf: ngs/terraform@0.0.1
workflows:
  tf:
    jobs:
      - tf/validate:
          <<: *secrets
          name: validate
      - tf/plan:
          <<: *secrets
          name: plan
          requires:
            - validate
      - tf/apply:
          name: apply
          requires:
            - plan
          filters:
            branches:
              only: master