version: 2.1

secrets: &secrets
#     context: cdk8s

aliases:
  params:
    path: &path
      type: "string"
      description: "Path to the terraform module"
    secrets: &secrets
      context: cdk8s

# codify structure of orb inline
orbs:
  # orb name @ top
  tf:
    # the 'tf' orb contains the following jobs
    jobs:
      # pass a map of jobs
      init: # init terraform directory
        executor: terraform-executor
        working_directory: "~/src"
        steps:
          - checkout
          - t:
            # nest the param under the command
              cmd_name: "init"
      # going to codify the rest of the "dummy" job declarations
      validate:
        executor: terraform-executor
        working_directory: "/src"
        steps:
          - checkout
          - t:
              cmd_name: "validate"
      plan:
        executor: terraform-executor
        working_directory: "/src"
        steps:
          - checkout
      apply:
        description: "Apply a Terraform plan"
        executor: terraform-executor
        working_directory: "/src"
        steps:
          - checkout
      destroy:
        executor: terraform-executor
        working_directory: "/src"
        steps:
          - checkout
    commands:
      t:
        parameters:
          cmd_name:
            type: string
            default: ""
        steps:
          - run:
              name: terraform << parameters.cmd_name >>
              command: terraform << parameters.cmd_name >>
    executors:
      terraform-executor:
        parameters:
          working_dir:
            type: string
            default: "~/src"
        # specify executor type
        docker:
          - image: hashicorp/terraform:light
        working_directory: << parameters.working_dir >>

workflows:
  plan-approve-apply:
    jobs:
      - tf/init:
          <<: *secrets
      - tf/validate:
          <<: *secrets
        