version: 2.1

secrets: &secrets
  context: cdk8s

orbs:
  terraform: circleci/terraform@1.0.1

jobs:
  test-terraform-lifecycle:
    executor: terraform/terraform-executor
    working_directory: "~/src"
    steps:
      - checkout
      - terraform/init:
          path: "."
      - terraform/validate:
          path: "."
      - terraform/fmt:
          path: "."
      - terraform/plan:
          path: "."
      - terraform/apply:
          path: "."
      - terraform/destroy:
          path: "."

workflows:
  validate-commands:
    jobs:
      - terraform/fmt:
          checkout: true
          <<: *secrets
      - terraform/validate:
          checkout: true
          <<: *secrets
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          persist-workspace: true
          <<: *secrets
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          <<: *secrets
          requires:
            - terraform/plan
      - terraform/destroy:
          <<: *secrets
          requires:
            - terraform/apply


