version: 2.1

# codify structure of orb inline
orbs:
  # orb name @ top
  tf:
    # the 'tf' orb contains the following jobs
    jobs:
      # pass a map of jobs
      init: # init terraform directory
        executor: terraform-executor
        working_directory: "~/src"
        steps:
          - t:
            # nest the param under the command
              cmd_name: "init"
    commands:
      t:
        parameters:
          cmd_name:
            type: string
            default: ""
        steps:
          - run: terraform << parameters.cmd_name >>
    executors:
      terraform-executor:
        parameters:
          working_dir:
            type: string
            default: "~/src"
        # specify executor type
        docker:
          - image: hashicorp/terraform:light
        working_directory: << parameters.working_dir >>

workflows:
  plan-approve-apply:
    jobs:
      - tf/init
        