version: 2.1

secrets: &secrets
  context: cdk8s

orbs:
  terraform: circleci/terraform@dev:alpha

jobs:
  test-terraform-lifecycle:
    executor: terraform/terraform-executor
    working_directory: "~/src"
    steps:
      - checkout
      - terraform/init:
          path: "."
      - terraform/validate:
          path: "."
      - terraform/fmt:
          path: "."
      - terraform/plan:
          path: "."
      - terraform/apply:
          path: "."
      - terraform/destroy:
          path: "."

workflows:
  validate-commands:
    jobs:
      - test-terraform-lifecycle:
          <<: *secrets
       # - terraform/plan:
       #     persist-workspace: true
       #     <<: *secrets
       # - terraform/apply:
       #     requires:
       #       - terraform/plan
       #     checkout: false
       #     attach-workspace: true
       #     <<: *secrets
