version: 2.1

jobs:
  terraform-plan:
    docker:
      - image: hashicorp/terraform:light
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Setup Terraform Credentials
          command: |
            mkdir -p ~/.terraform.d
            echo "{\"credentials\": {\"aedifexhack.jfrog.io\": {\"token\": \"${JFROG}\"}}}" > ~/.terraform.d/credentials.tfrc.json
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: |
            terraform plan \
              -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
              -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}"


  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Setup Terraform Credentials
          command: |
            mkdir -p ~/.terraform.d
            echo "{\"credentials\": {\"aedifexhack.jfrog.io\": {\"token\": \"${JFROG}\"}}}" > ~/.terraform.d/credentials.tfrc.json
      - run:
          name: Terraform Init
          command: terraform init
#      - run:
#          name: Terraform Apply
#          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - terraform-plan
      - terraform-approve:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - terraform-approve
