version: 2.1

orbs:
  artifactory-orb: jfrog/artifactory-orb@1.0.1

jobs:
  terraform-plan:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Configure artifactory backend
          command: sleep $(shuf -i 60-120 -n 1)
      - run:
          name: Setup Terraform Credentials
          command: |
            mkdir -p ~/.terraform.d
            echo "{\"credentials\": {\"aedifexhack.jfrog.io\": {\"token\": \"${JFROG}\"}}}" > ~/.terraform.d/credentials.tfrc.json
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: |
            terraform plan \
              -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
              -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}"


  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Configure artifactory backend
          command: sleep $(shuf -i 60-120 -n 1)
      - run:
          name: Setup Terraform Credentials
          command: |
            mkdir -p ~/.terraform.d
            echo "{\"credentials\": {\"aedifexhack.jfrog.io\": {\"token\": \"${JFROG}\"}}}" > ~/.terraform.d/credentials.tfrc.json
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Apply
          command: |
            terraform apply \
              -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
              -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
              --auto-approve

  iac-security-scanning:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run code security tests
          command: echo "code security" && sleep $(shuf -i 300-420 -n 1)

  compliance-checks:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run compliance checks
          command: echo "compliance checks" && sleep $(shuf -i 300-420 -n 1)

  cost-estimator:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Estimate infra costs
          command: echo "Estimate infra costs" && sleep $(shuf -i 300-420 -n 1)

  connect-artifactory:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Pull artifacts
          command: echo "Estimate infra costs" && sleep $(shuf -i 300-420 -n 1)

workflows:
  version: 2
  plan-approve-apply:
    jobs:
      - connect-artifactory
      - terraform-plan:
          requires:
            - connect-artifactory
      - iac-security-scanning
      - terraform-approve:
          type: approval
          requires:
            - terraform-plan
            - iac-security-scanning
      - compliance-checks:
          requires:
            - terraform-plan
      - cost-estimator:
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - terraform-approve
            - compliance-checks
            - cost-estimator
