version: 2.1

jobs:
  terraform-plan:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
#      - run:
#          name: Terraform Plan
#          command: terraform plan -out=tfplan

  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
#      - run:
#          name: Terraform Apply
#          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - terraform-plan
      - terraform-apply:
          requires:
            - terraform-plan
          filters:
            branches:
              only: main
